### PR TITLE
update new package name in readme

### PR DESCRIPTION
**Pull request by moisout**
Hi, i updated the new package (@freetube/yt-comment-scraper) in the installation and usage section of the readme.

### CODE REVIEW

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]

**Review by kommunarr — DISMISSED** [review]

**Review by PikachuEXE — DISMISSED** [review]

**Comment by PikachuEXE** [comment]
Nope won't auto merge

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — DISMISSED** [review]

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
GH really behaves in mysterious ways. I don't understand why it doesnt want to get merged.

**Review by peepo5 — DISMISSED** [review]

**Review by ChunkyProgrammer — DISMISSED** [review]

**Comment by PrestonN** [comment]
This PR will need to be redone and merged against the Development branch instead of the Master branch. There are different rules for merging into master which is why the auto merge isn't working. Please make this change for your PR and then it should work.

**Review by PikachuEXE — APPROVED** [review]
I didn't notice the merge target
Now it should be fine

**Review by kommunarr — APPROVED** [review]

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]

**Pull request merged**
