### PR TITLE
Add isOwner, isPinned & hasOwnerReplied to response object

### PR DESCRIPTION
**Pull request by ChunkyProgrammer**
Will be useful for when someone wants to implement these
https://github.com/FreeTubeApp/FreeTube/issues/1431
https://github.com/FreeTubeApp/FreeTube/issues/1432
https://github.com/FreeTubeApp/FreeTube/issues/1433

### CODE REVIEW

**Comment by ChunkyProgrammer** [comment]
If it's better for me to do multiple pull requests instead of all at once, let me know

**Comment by GilgusMaximus** [comment]
I think here it is fine. The code base is not so large and the features are all intermingled somewhat.

**Comment by GilgusMaximus** [comment]
For a new version though, it would be good to also take in the 'Official Artist' and 'Verified' checkmarks. Because these are displayed in the comments as well.

Verified is relatively clear and artist looks like this:
image

Must not be done in this PR. I added it for other packages already, so I can do this myself. But I then would add this in as well to make it more complete

**Comment by ChunkyProgrammer** [comment]
Sounds good to me, if you're already familiar with it then it'd probably be better if you add "Official Artist" and "Verified"

**Comment by GilgusMaximus** [comment]
Yeah sure. 
I'll check your code in the coming days. Have a lot of stuff to do outside of FT atm, so I am currently doing that stuff instead. I also saw your code on  yt-channel-info and will test and merge it as soon as possible

**Comment by GilgusMaximus** [comment]
So the code looks fine, test suite works and I do not see any problems with this :)
So thanks for adding this.

**Pull request merged**
